name: fluro
description: Fluro is a Flutter routing library that adds flexible routing options like wildcards, named parameters and clear route definitions.
version: 1.7.7
homepage: https://github.com/lukepighetti/fluro

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
